version: '3.6'
services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./.env
      - ./.env.development
      - ./.env.development.local
    ports:
      - '5432:5432'
